# Generated by Django 4.1.1 on 2023-10-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email1', models.CharField(default='', max_length=45)),
                ('password', models.CharField(default=False, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=45)),
                ('email', models.EmailField(default='', max_length=45)),
                ('phone', models.CharField(default='', max_length=10)),
                ('company', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=10)),
                ('brand', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=45)),
            ],
        ),
    ]
