# Generated by Django 4.1.1 on 2023-10-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loging',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.CharField(default=False, max_length=45),
        ),
    ]
