# Generated by Django 4.1.1 on 2023-10-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_loging_remove_register_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=45)),
                ('position', models.CharField(default='', max_length=45)),
                ('img', models.FileField(blank=True, null=True, upload_to='media')),
            ],
        ),
    ]
